url: http://inthevalleydsm.com/
baseurl:

#baseurl: /agency-jekyll-theme/

# Site settings
title: inthevalleydsm
email: joshmccall221@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: inthevalleydsm
  pic: inthevalley
  position: Lead Designer
  social:
    - title: twitter
      url: https://twitter.com/inthevalleydsm

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/inthevalleydsm
 
# Postal address (add as many lines as necessary)
address:
  - line: 1420 Locust St, 
  - line: Des Moines, IA 50309

# Build settings
markdown: kramdown
permalink: pretty
